# Install Ansible Roles
# ---------------------
# When making the Conductor image `ansible-galaxy install -r requirements.yml` is executed
# using this file. Follow the instructions at http://docs.ansible.com/ansible/galaxy.html
# to include any roles you want installed prior to running main.yml.
- src: AAROC.cvmfs-client-2-2
  version: v1.2.0